### PR TITLE
Copy to clipboard btn func

### PR DESCRIPTION
**Pull request by pandurijal**
Hi, Timmy!
After what we discuss on #1 here is what I propose. As I am avoiding the use of an external library for this feature, I have to change the color code tag from `p` to `input` hence the browser can get the value from the input. But it should works normally the same as it was. 

Feel free to add anything!

Screenshot 2020-10-04 at 22 43 16
Screenshot 2020-10-04 at 22 43 26

### CODE REVIEW

**Comment by timmybytes** [comment]
Looks great! Thanks for your help on this!

**Comment by pandurijal** [comment]
Yes anytime!
Oh ya I think you've got the typo on hacktoberfest label on the repo, hence committee found my PR ineligible hahaha

**Comment by timmybytes** [comment]
Nooo! Ugh, I'm so sorry for all this trouble!! I've fixed the tag, for what it's worth. That's what I get for trying to edit a repo right before bed.

**Comment by pandurijal** [comment]
No problem mate. Thanks for the bits of help. Feel free to contribute to my repo as well. Cheers!

**Pull request merged**
